// Interfaces voor trainingsdata
export interface Workout {
  day: string;
  date: string;
  type: 'swim' | 'bike' | 'run' | 'rest' | 'race';
  title: string;
  description: string;
  duration: string;
  distance?: string;
  intensity: 'rest' | 'easy' | 'moderate' | 'hard' | 'race';
  paceTarget?: string;
  isKeyWorkout?: boolean;
  fallback?: { duration: string; description: string };
}

export interface Week {
  number: number;
  dateStart: string;
  dateEnd: string;
  phase: string;
  phaseColor: string;
  totalHours: string;
  keyWorkout: string;
  sessions: Workout[];
}

export interface Race {
  name: string;
  date: string;
  target: string;
  type: 'marathon' | 'triathlon';
  distance?: string;
  priority?: 'A' | 'B' | 'C';
  status?: 'upcoming' | 'completed' | 'dns';
}

export interface AthleteProfile {
  name: string;
  marathonPR: string;
  ironmanPR: string;
  vo2max: number;
  thresholdPace: string;
  easyPace: string;
  intervalPace: string;
}

// Marathon pacing splits
export const marathonSplits = [
  { km: 5, pace: '4:05', time: '20:25', cumulative: '20:25', nutrition: 'Water' },
  { km: 10, pace: '4:01', time: '20:05', cumulative: '40:30', nutrition: 'Gel + water' },
  { km: 15, pace: '4:01', time: '20:05', cumulative: '1:00:35', nutrition: 'Water' },
  { km: 20, pace: '4:01', time: '20:05', cumulative: '1:20:40', nutrition: 'Gel + electrolytes' },
  { km: 25, pace: '4:00', time: '20:00', cumulative: '1:40:40', nutrition: 'Water' },
  { km: 30, pace: '4:00', time: '20:00', cumulative: '2:00:40', nutrition: 'Gel + water' },
  { km: 35, pace: '4:00', time: '20:00', cumulative: '2:20:40', nutrition: 'Electrolytes' },
  { km: 40, pace: '3:59', time: '19:55', cumulative: '2:40:35', nutrition: 'Gel' },
  { km: 42.2, pace: '3:58', time: '8:44', cumulative: '2:49:19', nutrition: 'Sprint finish!' },
];

// 70.3 Pacing targets
export const triathlonSplits = {
  swim: '35:00',
  t1: '3:00',
  bike: '2:22:00',
  t2: '2:00',
  run: '1:27:00',
  total: '4:29:00',
  bikeNutrition: ['Hour 0-30: 1 gel + 500ml sports drink', 'Hour 30-60: 1 energy bar + 500ml water', 'Hour 60-90: 1 gel + 500ml sports drink'],
};

// Athlete profile
export const athleteProfile: AthleteProfile = {
  name: 'Pepe',
  marathonPR: '3:01',
  ironmanPR: '9:56',
  vo2max: 61,
  thresholdPace: '3:58/km',
  easyPace: '5:00/km',
  intervalPace: '3:42/km',
};

// Race data
export const races: Race[] = [
  {
    name: 'Marathon Kopenhagen',
    date: '2026-05-10',
    target: '2:49:59',
    type: 'marathon',
    distance: '42.2 km',
    priority: 'A',
    status: 'upcoming',
  },
  {
    name: 'Half Ironman 70.3',
    date: '2026-06-07',
    target: '4:29:00',
    type: 'triathlon',
    distance: '113 km (1.9km swim + 90km bike + 21km run)',
    priority: 'A',
    status: 'upcoming',
  },
];

// Complete 9-week training plan
export const trainingPlan: Week[] = [
  // Week 1 - Marathon Build
  {
    number: 1,
    dateStart: '2026-04-06',
    dateEnd: '2026-04-12',
    phase: 'Marathon Build',
    phaseColor: 'bg-gradient-to-r from-red-600 to-red-400',
    totalHours: '8.5',
    keyWorkout: 'Long run 18km',
    sessions: [
      {
        day: 'Maandag',
        date: '2026-04-06',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Dinsdag',
        date: '2026-04-07',
        type: 'swim',
        title: 'Zwem interval',
        description: '6x500m op 8:00',
        duration: '50 min',
        distance: '3 km',
        intensity: 'moderate',
        paceTarget: '1:36/100m',
      },
      {
        day: 'Woensdag',
        date: '2026-04-08',
        type: 'bike',
        title: 'Bike steady state',
        description: 'Z2 watt zone',
        duration: '90 min',
        distance: '45 km',
        intensity: 'easy',
        paceTarget: '240W',
      },
      {
        day: 'Donderdag',
        date: '2026-04-09',
        type: 'run',
        title: 'Tempo run',
        description: '2x3km @ threshold',
        duration: '60 min',
        distance: '12 km',
        intensity: 'hard',
        paceTarget: '3:58/km',
      },
      {
        day: 'Vrijdag',
        date: '2026-04-10',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Zaterdag',
        date: '2026-04-11',
        type: 'bike',
        title: 'Long bike',
        description: 'Z2 conversatie tempo',
        duration: '120 min',
        distance: '60 km',
        intensity: 'moderate',
        paceTarget: '200W',
        isKeyWorkout: true,
      },
      {
        day: 'Zondag',
        date: '2026-04-12',
        type: 'run',
        title: 'Long run',
        description: 'Steady easy pace',
        duration: '150 min',
        distance: '18 km',
        intensity: 'easy',
        paceTarget: '5:00/km',
        isKeyWorkout: true,
      },
    ],
  },

  // Week 2 - Marathon Build
  {
    number: 2,
    dateStart: '2026-04-13',
    dateEnd: '2026-04-19',
    phase: 'Marathon Build',
    phaseColor: 'bg-gradient-to-r from-red-600 to-red-400',
    totalHours: '9.0',
    keyWorkout: 'Long run 20km',
    sessions: [
      {
        day: 'Maandag',
        date: '2026-04-13',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Dinsdag',
        date: '2026-04-14',
        type: 'run',
        title: 'Run interval',
        description: '5x2km @ hard',
        duration: '70 min',
        distance: '13 km',
        intensity: 'hard',
        paceTarget: '3:52/km',
      },
      {
        day: 'Woensdag',
        date: '2026-04-15',
        type: 'swim',
        title: 'Zwem distance',
        description: '3x800m aerobic',
        duration: '55 min',
        distance: '3.2 km',
        intensity: 'moderate',
        paceTarget: '1:45/100m',
      },
      {
        day: 'Donderdag',
        date: '2026-04-16',
        type: 'bike',
        title: 'Bike tempo',
        description: '3x10min @ VO2max',
        duration: '100 min',
        distance: '50 km',
        intensity: 'hard',
        paceTarget: '290W',
      },
      {
        day: 'Vrijdag',
        date: '2026-04-17',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Zaterdag',
        date: '2026-04-18',
        type: 'run',
        title: 'Marathon-pace run',
        description: '10km @ race pace',
        duration: '55 min',
        distance: '10 km',
        intensity: 'moderate',
        paceTarget: '4:00/km',
      },
      {
        day: 'Zondag',
        date: '2026-04-19',
        type: 'run',
        title: 'Long run',
        description: 'Steady easy',
        duration: '165 min',
        distance: '20 km',
        intensity: 'easy',
        paceTarget: '5:00/km',
        isKeyWorkout: true,
      },
    ],
  },

  // Week 3 - Marathon Build
  {
    number: 3,
    dateStart: '2026-04-20',
    dateEnd: '2026-04-26',
    phase: 'Marathon Build',
    phaseColor: 'bg-gradient-to-r from-red-600 to-red-400',
    totalHours: '8.0',
    keyWorkout: 'Long run 18km',
    sessions: [
      {
        day: 'Maandag',
        date: '2026-04-20',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Dinsdag',
        date: '2026-04-21',
        type: 'bike',
        title: 'Bike sweet spot',
        description: '4x8min FTP',
        duration: '90 min',
        distance: '45 km',
        intensity: 'hard',
        paceTarget: '280W',
      },
      {
        day: 'Woensdag',
        date: '2026-04-22',
        type: 'swim',
        title: 'Zwem threshold',
        description: '2x1600m tempo',
        duration: '50 min',
        distance: '3.2 km',
        intensity: 'hard',
        paceTarget: '1:40/100m',
      },
      {
        day: 'Donderdag',
        date: '2026-04-23',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Vrijdag',
        date: '2026-04-24',
        type: 'run',
        title: 'Easy recovery run',
        description: 'Conversatie tempo',
        duration: '40 min',
        distance: '8 km',
        intensity: 'easy',
        paceTarget: '5:00/km',
      },
      {
        day: 'Zaterdag',
        date: '2026-04-25',
        type: 'bike',
        title: 'Long bike',
        description: 'Z2 steady state',
        duration: '110 min',
        distance: '55 km',
        intensity: 'moderate',
        paceTarget: '200W',
      },
      {
        day: 'Zondag',
        date: '2026-04-26',
        type: 'run',
        title: 'Long run',
        description: 'Easy pace practice',
        duration: '150 min',
        distance: '18 km',
        intensity: 'easy',
        paceTarget: '5:00/km',
        isKeyWorkout: true,
      },
    ],
  },

  // Week 4 - Taper
  {
    number: 4,
    dateStart: '2026-04-27',
    dateEnd: '2026-05-03',
    phase: 'Taper',
    phaseColor: 'bg-gradient-to-r from-orange-600 to-orange-400',
    totalHours: '5.5',
    keyWorkout: 'Marathon race week preparation',
    sessions: [
      {
        day: 'Maandag',
        date: '2026-04-27',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Dinsdag',
        date: '2026-04-28',
        type: 'run',
        title: 'Easy run',
        description: 'Shake out legs',
        duration: '35 min',
        distance: '7 km',
        intensity: 'easy',
        paceTarget: '5:00/km',
      },
      {
        day: 'Woensdag',
        date: '2026-04-29',
        type: 'swim',
        title: 'Zwem short',
        description: 'Technique focus',
        duration: '30 min',
        distance: '1.5 km',
        intensity: 'easy',
        paceTarget: '2:00/100m',
      },
      {
        day: 'Donderdag',
        date: '2026-04-30',
        type: 'bike',
        title: 'Easy bike',
        description: 'Spin legs',
        duration: '45 min',
        distance: '22 km',
        intensity: 'easy',
        paceTarget: '160W',
      },
      {
        day: 'Vrijdag',
        date: '2026-05-01',
        type: 'rest',
        title: 'Rust',
        description: 'Race eve preparation',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Zaterdag',
        date: '2026-05-02',
        type: 'run',
        title: 'Short shake out',
        description: 'Easy + 3x1min strides',
        duration: '30 min',
        distance: '5 km',
        intensity: 'easy',
        paceTarget: '5:00/km',
      },
      {
        day: 'Zondag',
        date: '2026-05-03',
        type: 'race',
        title: 'Marathon Kopenhagen',
        description: 'Target: 2:49:59',
        duration: '2:50',
        distance: '42.2 km',
        intensity: 'race',
        paceTarget: '4:00/km',
        isKeyWorkout: true,
      },
    ],
  },

  // Week 5 - Recovery (post-marathon)
  {
    number: 5,
    dateStart: '2026-05-04',
    dateEnd: '2026-05-10',
    phase: 'Recovery',
    phaseColor: 'bg-gradient-to-r from-purple-600 to-purple-400',
    totalHours: '4.0',
    keyWorkout: 'Recovery and assessment',
    sessions: [
      {
        day: 'Maandag',
        date: '2026-05-04',
        type: 'rest',
        title: 'Rust',
        description: 'Post-race recovery',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Dinsdag',
        date: '2026-05-05',
        type: 'swim',
        title: 'Easy swim',
        description: 'Recovery swim',
        duration: '30 min',
        distance: '1.5 km',
        intensity: 'easy',
        paceTarget: '2:00/100m',
      },
      {
        day: 'Woensdag',
        date: '2026-05-06',
        type: 'rest',
        title: 'Rust',
        description: 'Active recovery',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Donderdag',
        date: '2026-05-07',
        type: 'run',
        title: 'Easy run',
        description: 'Recovery jog',
        duration: '30 min',
        distance: '6 km',
        intensity: 'easy',
        paceTarget: '5:00/km',
      },
      {
        day: 'Vrijdag',
        date: '2026-05-08',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Zaterdag',
        date: '2026-05-09',
        type: 'bike',
        title: 'Easy bike',
        description: 'Spin recovery',
        duration: '45 min',
        distance: '22 km',
        intensity: 'easy',
        paceTarget: '160W',
      },
      {
        day: 'Zondag',
        date: '2026-05-10',
        type: 'swim',
        title: 'Pool time',
        description: 'Recovery swim',
        duration: '30 min',
        distance: '1.5 km',
        intensity: 'easy',
        paceTarget: '2:00/100m',
      },
    ],
  },

  // Week 6 - 70.3 Build Start
  {
    number: 6,
    dateStart: '2026-05-11',
    dateEnd: '2026-05-17',
    phase: '70.3 Build',
    phaseColor: 'bg-gradient-to-r from-blue-600 to-blue-400',
    totalHours: '7.5',
    keyWorkout: '70.3 brick workout',
    sessions: [
      {
        day: 'Maandag',
        date: '2026-05-11',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Dinsdag',
        date: '2026-05-12',
        type: 'swim',
        title: 'Zwem distance',
        description: '4x600m aerobic',
        duration: '55 min',
        distance: '2.8 km',
        intensity: 'moderate',
        paceTarget: '1:50/100m',
      },
      {
        day: 'Woensdag',
        date: '2026-05-13',
        type: 'bike',
        title: 'Bike sweet spot',
        description: '3x10min FTP',
        duration: '95 min',
        distance: '47 km',
        intensity: 'hard',
        paceTarget: '280W',
      },
      {
        day: 'Donderdag',
        date: '2026-05-14',
        type: 'run',
        title: 'Tempo run',
        description: '2x2km @ threshold',
        duration: '50 min',
        distance: '10 km',
        intensity: 'hard',
        paceTarget: '3:58/km',
      },
      {
        day: 'Vrijdag',
        date: '2026-05-15',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Zaterdag',
        date: '2026-05-16',
        type: 'bike',
        title: 'Long bike',
        description: 'Z2 conversatie',
        duration: '120 min',
        distance: '60 km',
        intensity: 'moderate',
        paceTarget: '200W',
        isKeyWorkout: true,
      },
      {
        day: 'Zondag',
        date: '2026-05-17',
        type: 'run',
        title: '70.3 run pace',
        description: '8km @ race pace',
        duration: '60 min',
        distance: '12 km',
        intensity: 'moderate',
        paceTarget: '4:05/km',
      },
    ],
  },

  // Week 7 - 70.3 Build Continued
  {
    number: 7,
    dateStart: '2026-05-18',
    dateEnd: '2026-05-24',
    phase: '70.3 Build',
    phaseColor: 'bg-gradient-to-r from-blue-600 to-blue-400',
    totalHours: '8.5',
    keyWorkout: 'Brick workout bike + run',
    sessions: [
      {
        day: 'Maandag',
        date: '2026-05-18',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Dinsdag',
        date: '2026-05-19',
        type: 'run',
        title: 'Run interval',
        description: '6x800m hard',
        duration: '60 min',
        distance: '11 km',
        intensity: 'hard',
        paceTarget: '3:45/km',
      },
      {
        day: 'Woensdag',
        date: '2026-05-20',
        type: 'swim',
        title: 'Zwem threshold',
        description: '2x1500m tempo',
        duration: '60 min',
        distance: '3.5 km',
        intensity: 'hard',
        paceTarget: '1:45/100m',
      },
      {
        day: 'Donderdag',
        date: '2026-05-21',
        type: 'bike',
        title: 'VO2max intervals',
        description: '5x4min @ VO2',
        duration: '90 min',
        distance: '45 km',
        intensity: 'hard',
        paceTarget: '310W',
      },
      {
        day: 'Vrijdag',
        date: '2026-05-22',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Zaterdag',
        date: '2026-05-23',
        type: 'bike',
        title: 'Brick: bike + run',
        description: '90min bike (Z2) + 20min run',
        duration: '140 min',
        distance: '45 km bike + 4 km run',
        intensity: 'moderate',
        paceTarget: '200W + 4:05/km',
        isKeyWorkout: true,
      },
      {
        day: 'Zondag',
        date: '2026-05-24',
        type: 'run',
        title: 'Easy run',
        description: 'Recovery run',
        duration: '45 min',
        distance: '9 km',
        intensity: 'easy',
        paceTarget: '5:00/km',
      },
    ],
  },

  // Week 8 - 70.3 Taper
  {
    number: 8,
    dateStart: '2026-05-25',
    dateEnd: '2026-05-31',
    phase: '70.3 Taper',
    phaseColor: 'bg-gradient-to-r from-cyan-600 to-cyan-400',
    totalHours: '5.0',
    keyWorkout: '70.3 race week taper',
    sessions: [
      {
        day: 'Maandag',
        date: '2026-05-25',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Dinsdag',
        date: '2026-05-26',
        type: 'swim',
        title: 'Easy swim',
        description: 'Technique focus',
        duration: '30 min',
        distance: '1.5 km',
        intensity: 'easy',
        paceTarget: '2:00/100m',
      },
      {
        day: 'Woensdag',
        date: '2026-05-27',
        type: 'bike',
        title: 'Easy bike',
        description: 'Spin legs',
        duration: '45 min',
        distance: '22 km',
        intensity: 'easy',
        paceTarget: '160W',
      },
      {
        day: 'Donderdag',
        date: '2026-05-28',
        type: 'run',
        title: 'Easy run',
        description: 'Recovery jog',
        duration: '30 min',
        distance: '6 km',
        intensity: 'easy',
        paceTarget: '5:00/km',
      },
      {
        day: 'Vrijdag',
        date: '2026-05-29',
        type: 'rest',
        title: 'Rust',
        description: 'Race eve prep',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Zaterdag',
        date: '2026-05-30',
        type: 'swim',
        title: 'Warm-up swim',
        description: 'Easy + technique',
        duration: '25 min',
        distance: '1 km',
        intensity: 'easy',
        paceTarget: '2:00/100m',
      },
      {
        day: 'Zondag',
        date: '2026-05-31',
        type: 'race',
        title: 'Half Ironman 70.3',
        description: 'Target: 4:29:00',
        duration: '4:30',
        distance: '113 km',
        intensity: 'race',
        isKeyWorkout: true,
      },
    ],
  },

  // Week 9 - 70.3 Race Week
  {
    number: 9,
    dateStart: '2026-06-01',
    dateEnd: '2026-06-07',
    phase: 'Race Week',
    phaseColor: 'bg-gradient-to-r from-yellow-600 to-yellow-400',
    totalHours: '2.0',
    keyWorkout: '70.3 Triathlon Race',
    sessions: [
      {
        day: 'Maandag',
        date: '2026-06-01',
        type: 'rest',
        title: 'Rust',
        description: 'Post-race recovery',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Dinsdag',
        date: '2026-06-02',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Woensdag',
        date: '2026-06-03',
        type: 'swim',
        title: 'Easy swim',
        description: 'Recovery swim',
        duration: '25 min',
        distance: '1 km',
        intensity: 'easy',
        paceTarget: '2:00/100m',
      },
      {
        day: 'Donderdag',
        date: '2026-06-04',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Vrijdag',
        date: '2026-06-05',
        type: 'run',
        title: 'Easy run',
        description: 'Easy jog',
        duration: '25 min',
        distance: '5 km',
        intensity: 'easy',
        paceTarget: '5:00/km',
      },
      {
        day: 'Zaterdag',
        date: '2026-06-06',
        type: 'rest',
        title: 'Rust',
        description: 'Recovery day',
        duration: '-',
        intensity: 'rest',
      },
      {
        day: 'Zondag',
        date: '2026-06-07',
        type: 'rest',
        title: 'Celebration!',
        description: 'Recovery and celebration',
        duration: '-',
        intensity: 'rest',
      },
    ],
  },
];
